import type { WorkspaceBillingControl } from "./workspaceBilling";

export async function getWorkspaceBillingControl(
  db: D1Database,
  workspaceId: string,
): Promise<WorkspaceBillingControl | null> {
  const row = await db
    .prepare(
      `SELECT ledger_object_name,
              stripe_customer_id,
              stripe_subscription_id,
              stripe_subscription_item_id,
              self_service_subscription_plan,
              self_service_subscription_status,
              stripe_subscription_current_period_start,
              stripe_subscription_current_period_end,
              self_service_subscription_invoice_id,
              self_service_subscription_invoice_status,
              self_service_subscription_hosted_invoice_url,
              scheduled_entitlement_plan,
              scheduled_entitlement_effective_at,
              enterprise_deal_status,
              plan_override_plan,
              plan_override_start_at,
              plan_override_end_at,
              plan_override_reason,
              plan_override_created_by_user_id,
              plan_override_created_at,
              payment_required_plan_override_plan,
              payment_required_plan_override_start_at,
              payment_required_plan_override_end_at,
              payment_required_plan_override_reason,
              payment_required_plan_override_created_by_user_id,
              payment_required_plan_override_created_at,
              payment_required_plan_override_amount_minor,
              payment_required_plan_override_currency,
              payment_required_plan_override_collection_mode,
              payment_required_plan_override_invoice_id,
              payment_required_plan_override_invoice_status,
              payment_required_plan_override_hosted_invoice_url,
              payment_required_plan_override_paid_at,
              enterprise_ramp_up_status,
              enterprise_ramp_up_duration_months,
              enterprise_billing_cycle_start_date,
              enterprise_ramp_up_collection_mode,
              enterprise_ramp_up_invoice_review_enabled,
              enterprise_ramp_up_reason,
              enterprise_ramp_up_created_by_user_id,
              enterprise_ramp_up_created_at,
              enterprise_ramp_up_last_invoice_period_start,
              enterprise_ramp_up_last_invoice_period_end,
              enterprise_ramp_up_last_invoice_id,
              enterprise_ramp_up_last_invoice_status,
              enterprise_ramp_up_last_invoice_hosted_url,
              enterprise_ramp_up_last_invoiced_at,
              enterprise_annual_status,
              enterprise_annual_monthly_minimum_allowance,
              enterprise_annual_per_page_price_minor,
              enterprise_annual_yearly_amount_minor,
              enterprise_annual_collection_mode,
              enterprise_annual_invoice_review_enabled,
              enterprise_annual_reason,
              enterprise_annual_created_by_user_id,
              enterprise_annual_created_at,
              enterprise_annual_upfront_invoice_id,
              enterprise_annual_upfront_invoice_status,
              enterprise_annual_upfront_invoice_hosted_url,
              enterprise_annual_upfront_invoice_paid_at,
              enterprise_annual_last_overage_invoice_period_start,
              enterprise_annual_last_overage_invoice_period_end,
              enterprise_annual_last_overage_invoice_id,
              enterprise_annual_last_overage_invoice_status,
              enterprise_annual_last_overage_invoice_hosted_url,
              enterprise_annual_last_overage_invoiced_at,
              no_billing_enabled,
              no_billing_reason,
              no_billing_updated_by_user_id,
              no_billing_updated_at
       FROM workspace_billing_controls
       WHERE workspace_id = ?
       LIMIT 1`,
    )
    .bind(workspaceId)
    .first<WorkspaceBillingControl>();

  return row || null;
}
