import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";

describe("Worker configuration", () => {
  it("exposes the EMAIL binding through real Cloudflare Email Sending in local development", async () => {
    const configText = await readFile(new URL("../wrangler.jsonc", import.meta.url), "utf8");
    const config = Function(`"use strict"; return (${configText});`)();

    expect(config.send_email).toContainEqual({
      name: "EMAIL",
      remote: true,
    });
  });

  it("configures the Workspace product store as a SQLite-backed Durable Object", async () => {
    const configText = await readFile(new URL("../wrangler.jsonc", import.meta.url), "utf8");
    const config = Function(`"use strict"; return (${configText});`)();

    expect(config.durable_objects?.bindings).toContainEqual({
      name: "WORKSPACE_PRODUCT_STORE",
      class_name: "WorkspaceProductStore",
    });
    expect(config.migrations).toContainEqual({
      tag: "v1_workspace_product_store",
      new_sqlite_classes: ["WorkspaceProductStore"],
    });
  });

  it("configures the Workspace billing ledger as a SQLite-backed Durable Object", async () => {
    const configText = await readFile(new URL("../wrangler.jsonc", import.meta.url), "utf8");
    const config = Function(`"use strict"; return (${configText});`)();

    expect(config.durable_objects?.bindings).toContainEqual({
      name: "WORKSPACE_BILLING_LEDGER",
      class_name: "WorkspaceBillingLedger",
    });
    expect(config.migrations).toContainEqual({
      tag: "v2_workspace_billing_ledger",
      new_sqlite_classes: ["WorkspaceBillingLedger"],
    });
  });

  it("exposes Workspace product analytics through Workers Analytics Engine", async () => {
    const configText = await readFile(new URL("../wrangler.jsonc", import.meta.url), "utf8");
    const config = Function(`"use strict"; return (${configText});`)();

    expect(config.analytics_engine_datasets).toContainEqual({
      binding: "WORKSPACE_PRODUCT_ANALYTICS",
      dataset: "workspace_product_analytics",
    });
  });

  it("keeps Stripe catalog identifiers and secrets out of checked-in vars", async () => {
    const configText = await readFile(new URL("../wrangler.jsonc", import.meta.url), "utf8");
    const config = Function(`"use strict"; return (${configText});`)();

    expect(config.vars).not.toHaveProperty("STRIPE_PRO_MONTHLY_PRICE_ID");
    expect(config.vars).not.toHaveProperty("STRIPE_MAX_MONTHLY_PRICE_ID");
    expect(Object.keys(config.vars).filter((key) => key.startsWith("STRIPE_CREDIT_PACK_"))).toEqual([]);
    expect(Object.keys(config.vars).filter((key) => key.endsWith("_PRODUCT_ID"))).toEqual([]);
    expect(config.vars).not.toHaveProperty("STRIPE_CHECKOUT_SUCCESS_URL");
    expect(config.vars).not.toHaveProperty("STRIPE_CHECKOUT_CANCEL_URL");
    expect(config.vars).not.toHaveProperty("STRIPE_API_KEY");
    expect(config.vars).not.toHaveProperty("STRIPE_WEBHOOK_SECRET");
  });

  it("declares production deployment values as required Worker secrets and generated types", async () => {
    const configText = await readFile(new URL("../wrangler.jsonc", import.meta.url), "utf8");
    const config = Function(`"use strict"; return (${configText});`)();
    const generatedTypes = await readFile(new URL("../worker-configuration.d.ts", import.meta.url), "utf8");

    const requiredSecrets = [
      "AI_GATEWAY_TOKEN",
      "BETTER_AUTH_SECRET",
      "GOOGLE_CLIENT_ID",
      "GOOGLE_CLIENT_SECRET",
      "STRIPE_API_KEY",
      "STRIPE_WEBHOOK_SECRET",
      "STRIPE_PRO_MONTHLY_PRICE_ID",
      "STRIPE_MAX_MONTHLY_PRICE_ID",
    ];

    expect(config.secrets?.required).toEqual(requiredSecrets);
    expect(config.vars).not.toHaveProperty("STRIPE_PRO_MONTHLY_PRICE_ID");
    expect(config.vars).not.toHaveProperty("STRIPE_MAX_MONTHLY_PRICE_ID");

    for (const secretName of requiredSecrets) {
      expect(generatedTypes).toContain(`${secretName}: string;`);
    }
    expect(generatedTypes).toContain('Generated by Wrangler by running `wrangler types`');
  });

  it("documents one production deploy path through preflight and the repo-root secrets file", async () => {
    const backendPackage = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
    const rootPackage = JSON.parse(await readFile(new URL("../../package.json", import.meta.url), "utf8"));
    const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
    const gitignore = await readFile(new URL("../../.gitignore", import.meta.url), "utf8");

    expect(rootPackage.scripts.deploy).toBe("npm run deploy:prod --prefix backend");
    expect(backendPackage.scripts["preflight:prod"]).toBe("node scripts/productionPreflight.mjs");
    expect(backendPackage.scripts.deploy).toBe("npm run deploy:prod");
    expect(backendPackage.scripts["deploy:prod"]).toBe("npm run preflight:prod && wrangler deploy --secrets-file ../.vars");

    expect(gitignore.split(/\r?\n/)).toContain(".vars");
    expect(readme).toContain("repo-root `.vars`");
    expect(readme).toContain("dotenv");
    expect(readme).toContain("npm run preflight:prod");
    expect(readme).toContain("wrangler deploy --secrets-file ../.vars");
    expect(readme).toContain("STRIPE_PRO_MONTHLY_PRICE_ID");
    expect(readme).toContain("STRIPE_MAX_MONTHLY_PRICE_ID");
    expect(readme).not.toMatch(/\b(?:sk|rk)_(?:test|live)_[A-Za-z0-9]+\b/);
    expect(readme).not.toMatch(/\bwhsec_[A-Za-z0-9]+\b/);
  });

  it("keeps the production Worker launch configuration and bindings explicit", async () => {
    const configText = await readFile(new URL("../wrangler.jsonc", import.meta.url), "utf8");
    const config = Function(`"use strict"; return (${configText});`)();

    expect(config.compatibility_date).toBe("2026-06-06");
    expect(config.compatibility_flags).toContain("nodejs_compat");
    expect(config.workers_dev).toBe(false);
    expect(config.routes).toContainEqual({
      pattern: "extract.t3m.uk",
      custom_domain: true,
    });
    expect(config.assets).toMatchObject({
      directory: "../frontend/dist",
      binding: "ASSETS",
      run_worker_first: true,
      not_found_handling: "single-page-application",
    });
    expect(config.d1_databases).toContainEqual({
      binding: "DB",
      database_name: "document-extraction-db",
      database_id: "7a6653a9-97b9-46af-bd07-bddcccaa10a9",
      migrations_dir: "migrations",
    });
    expect(config.durable_objects?.bindings).toEqual(
      expect.arrayContaining([
        { name: "WORKSPACE_PRODUCT_STORE", class_name: "WorkspaceProductStore" },
        { name: "WORKSPACE_BILLING_LEDGER", class_name: "WorkspaceBillingLedger" },
      ]),
    );
    expect(config.r2_buckets).toContainEqual({
      binding: "SOURCE_FILES_BUCKET",
      bucket_name: "document-extraction-source-files",
    });
    expect(config.queues?.producers).toContainEqual({
      binding: "EXTRACTION_JOBS_QUEUE",
      queue: "document-extraction-jobs",
    });
    expect(config.queues?.consumers).toContainEqual({
      queue: "document-extraction-jobs",
      max_batch_size: 1,
      max_batch_timeout: 3,
      max_retries: 5,
    });
    expect(config.workflows).toContainEqual({
      name: "document-processing-workflow",
      binding: "DOCUMENT_PROCESSING_WORKFLOW",
      class_name: "DocumentProcessingWorkflow",
    });
    expect(config.analytics_engine_datasets).toContainEqual({
      binding: "WORKSPACE_PRODUCT_ANALYTICS",
      dataset: "workspace_product_analytics",
    });
    expect(config.send_email).toContainEqual({
      name: "EMAIL",
      remote: true,
    });
  });

  it("configures and documents production scheduled billing execution without secret values", async () => {
    const configText = await readFile(new URL("../wrangler.jsonc", import.meta.url), "utf8");
    const config = Function(`"use strict"; return (${configText});`)();
    const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");

    expect(config.triggers?.crons).toEqual(["17 * * * *"]);
    expect(readme).toContain("Production scheduled billing");
    expect(readme).toContain("17 * * * *");
    expect(readme).toContain("scheduled()");
    expect(readme).toContain("Cron Trigger");
    expect(readme).toContain("Workers Logs");
    expect(readme).not.toMatch(/\b(?:sk|rk)_(?:test|live)_[A-Za-z0-9]+\b/);
    expect(readme).not.toMatch(/\bwhsec_[A-Za-z0-9]+\b/);
  });

  it("configures scheduled billing observability through Workers Logs without secret values", async () => {
    const configText = await readFile(new URL("../wrangler.jsonc", import.meta.url), "utf8");
    const config = Function(`"use strict"; return (${configText});`)();
    const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");

    expect(config.observability).toMatchObject({
      enabled: true,
      head_sampling_rate: 1,
      logs: {
        enabled: true,
        invocation_logs: true,
      },
    });
    expect(readme).toContain("structured non-secret scheduled billing logs");
    expect(readme).toContain("billing.scheduled.workspace_failed");
    expect(configText).not.toMatch(/\b(?:sk|rk)_(?:test|live)_[A-Za-z0-9]+\b/);
    expect(configText).not.toMatch(/\bwhsec_[A-Za-z0-9]+\b/);
    expect(readme).not.toMatch(/\b(?:sk|rk)_(?:test|live)_[A-Za-z0-9]+\b/);
    expect(readme).not.toMatch(/\bwhsec_[A-Za-z0-9]+\b/);
  });

  it("documents Stripe billing secrets and webhook setup without secret values", async () => {
    const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");

    expect(readme).toContain("STRIPE_API_KEY");
    expect(readme).toContain("STRIPE_WEBHOOK_SECRET");
    expect(readme).toContain("STRIPE_WEBHOOK_SECRET_NEXT");
    expect(readme).toContain("/v1/billing/stripe/webhook");
    expect(readme).toContain("stripe listen --forward-to http://localhost:8787/v1/billing/stripe/webhook");
    expect(readme).toContain("checkout.session.async_payment_succeeded");
    expect(readme).toContain("invoice.payment_action_required");
    expect(readme).toContain("invoice.marked_uncollectible");
    expect(readme).toContain("customer.subscription.resumed");
    expect(readme).not.toMatch(/\b(?:sk|rk)_(?:test|live)_[A-Za-z0-9]+\b/);
    expect(readme).not.toMatch(/\bwhsec_[A-Za-z0-9]+\b/);
  });

  it("keeps the Stripe REST request safety contract centralized", async () => {
    const billingSource = await readFile(new URL("./api/billing.ts", import.meta.url), "utf8");
    const stripeFetchCalls = Array.from(billingSource.matchAll(/fetch\([\s\S]*?\n\s*\}\);/g))
      .filter((match) => {
        const contextStart = Math.max(0, match.index - 300);
        const context = `${billingSource.slice(contextStart, match.index)}\n${match[0]}`;
        return context.includes("https://api.stripe.com/");
      })
      .map((match) => match[0]);

    expect(stripeFetchCalls.length).toBeGreaterThan(0);
    expect(billingSource).toContain('const STRIPE_API_VERSION = "2026-05-27.dahlia";');
    expect(billingSource.match(/"stripe-version": "2026-05-27\.dahlia"/g)).toBeNull();
    expect(billingSource).not.toContain("payment_method_types");

    for (const fetchCall of stripeFetchCalls) {
      expect(fetchCall).toContain('"stripe-version": STRIPE_API_VERSION');
      if (fetchCall.includes('method: "POST"')) {
        expect(fetchCall).toContain('"idempotency-key"');
      }
    }
  });

  it("documents the Stripe restricted API key production contract", async () => {
    const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");

    expect(readme).toContain("Stripe restricted API key permissions");
    expect(readme).toContain("Customers: read and write");
    expect(readme).toContain("Checkout Sessions: create, read, and list");
    expect(readme).toContain("Subscriptions: read, update, and cancel");
    expect(readme).toContain("Invoices: create, read, list, and finalize");
    expect(readme).toContain("Invoice Items: create");
    expect(readme).toContain("Billing reconciliation reads");
    expect(readme).toContain("Stripe request logs");
    expect(readme).toContain("live webhook endpoint event API version");
    expect(readme).toContain("owner, expiry date, reason, and rotation plan");
    expect(readme).not.toMatch(/\b(?:sk|rk)_(?:test|live)_[A-Za-z0-9]+\b/);
    expect(readme).not.toMatch(/\bwhsec_[A-Za-z0-9]+\b/);
  });

  it("documents live Stripe Price ID separation and preflight read permissions", async () => {
    const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");

    expect(readme).toContain("Price IDs do not reveal test mode or live mode by prefix");
    expect(readme).toContain("livemode");
    expect(readme).toContain("active");
    expect(readme).toContain("GBP");
    expect(readme).toContain("monthly recurring");
    expect(readme).toContain("code-owned Workspace billing catalog");
    expect(readme).toContain("Webhook Endpoints: read");
    expect(readme).toContain("STRIPE_PRO_MONTHLY_PRICE_ID");
    expect(readme).toContain("STRIPE_MAX_MONTHLY_PRICE_ID");
    expect(readme).not.toMatch(/\bprice_[A-Za-z0-9]+\b/);
    expect(readme).not.toMatch(/\b(?:sk|rk)_(?:test|live)_[A-Za-z0-9]+\b/);
    expect(readme).not.toMatch(/\bwhsec_[A-Za-z0-9]+\b/);
  });
});
